## Copyright (c) 2022, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deployment OCI IOT Wearable Application"
stackDescription: "Deployment OCI IOT Wearable Application"
description: "Deployment on OCI IOT Wearable Application using OCI Resources."
schemaVersion: 0.0.0
version: "20221013"
locale: "en"

#################
# Variable Groups
#################
variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - compartment_ocid
  - user_ocid
  - fingerprint
  - private_key_path
  - region
  - app_name
  - oci_user_name
  - oci_user_authtoken
  - release
  - gateway_displayname
  - gateway_visibility
  - path_prefix
  - VCN-CIDR
  - Public-Subnet-CIDR
  - Private-Subnet-CIDR
  - availability_domain_name
  - mysql_instance_compartment_name
  - mysql_network_compartment_name
  - mysql_instance_compartment_ocid
  - mysql_network_compartment_ocid
  - mysql_db_system_admin_password
  - mysql_db_system_admin_username
  - mysql_db_system_backup_policy_is_enabled
  - mysql_db_system_backup_policy_retention_in_days
  - mysql_db_system_backup_policy_window_start_time
  - mysql_db_system_data_storage_size_in_gb
  - mysql_db_system_description
  - mysql_db_system_freeform_tags
  - mysql_db_system_is_highly_available
  - mysql_db_system_port
  - mysql_db_system_port_x
  - mysql_shape_name
  - mysql_heatwave_enabled
  - mysql_heatwave_cluster_size
  - mysql_heatwave_shape
  - bucket_access_type
  - bucket_auto_tiering
  - bucket_storage_tier
  - bucket_versioning
  - vault_vault_type
  - vault_key_shape_algorithm
  - key_key_shape_length
  - vault_key_protection_mode
  - vault_app_env_user
  - stream_partition_count
  - stream_retention_in_hours
  - oci_queue_ocid
  - auth_profile
  - email_domain_name
  - sender_email_address
  - container_repository_is_public
  - deploy_artifact_argument_substitution_mode
  - project_logging_config_retention_period_in_days
  - project_description
  - repository_name
  - repository_default_branch
  - repository_description
  - git_repo
  - git_repo_name
  - buildparam_baseimage_notificationservice
  - repository_repository_type
  - build_pipeline_stage_build_pipeline_stage_type
  - build_pipeline_stage_build_source_collection_items_connection_type
  - build_pipeline_stage_build_source_collection_items_branch
  - build_pipeline_stage_build_source_collection_items_name
  - notification_buildspec
  - tcpserver_buildspec
  - adminapi_buildspec
  - adminapi_authorizer_buildspec
  - build_pipeline_stage_display_name
  - build_pipeline_stage_image
  - build_pipeline_stage_wait_criteria_wait_duration
  - build_pipeline_stage_wait_criteria_wait_type
  - build_pipeline_stage_stage_execution_timeout_in_seconds
  - build_pipeline_stage_deliver_artifact_stage_type
  - deliver_artifact_stage_display_name
  - build_pipeline_stage_deploy_stage_type
  - deploy_stage_display_name
  - build_pipeline_stage_is_pass_all_parameters_enabled
  - oke_deploy_rollback_policy
  - oke_namespace
  - oke_externalsecret_operator_url
  - metric_server_version

- title: "Required Configuration"
  visible: true  
  variables:
    - oci_user_name
    - oci_user_authtoken
    - show_advanced
    - mysql_db_system_admin_username
    - mysql_db_system_admin_password
    - oci_queue_ocid

